export const HEALTH_CONDITIONS = [
  { value: "alergia", label: "Alergia" },
  { value: "asma", label: "Asma" },
  { value: "autismo", label: "Autismo" },
  { value: "diabetes", label: "Diabetes" },
  { value: "epilepsia", label: "Epilepsia" },
  { value: "problema_cardiaco", label: "Problema Cardíaco" },
  { value: "tdah", label: "TDAH" },
  { value: "tda", label: "TDA" },
  { value: "ansiedade", label: "Ansiedade" },
  { value: "depressao", label: "Depressão" },
  { value: "deficiencia_auditiva", label: "Deficiência Auditiva" },
  { value: "deficiencia_visual", label: "Deficiência Visual" },
  { value: "deficiencia_motora", label: "Deficiência Motora" },
  { value: "sindromes", label: "Síndromes" },
  { value: "outro", label: "Outro" },
] as const;

export const HEALTH_CONDITION_VALUES = HEALTH_CONDITIONS.map((c) => c.value);

export const COLUMN_ALIASES: Record<string, string[]> = {
  nome: [
    "nome completo",
    "nome",
    "participante",
    "nome do participante",
    "aluno",
    "membro",
    "nome do aluno",
    "nome do membro",
    "full name",
    "name",
  ],
  sexo: [
    "sexo",
    "genero",
    "gênero",
    "gender",
    "sex",
    "sexo biologico",
    "sexo biológico",
  ],
  dataNascimento: [
    "data de nascimento",
    "nascimento",
    "dt nascimento",
    "data nasc",
    "data nascimento",
    "datanascimento",
    "nasc",
    "birthday",
    "birth date",
    "birth",
  ],
  idade: [
    "idade",
    "age",
    "anos",
  ],
  cpf: [
    "cpf",
    "documento",
    "documento fiscal",
    "cpf do participante",
  ],
  rg: [
    "rg",
    "identidade",
    "rg do participante",
  ],
  tipoSanguineo: [
    "tipo sanguíneo",
    "tipo sanguineo",
    "tipo sangue",
    "blood type",
    "sangue",
  ],
  igreja: [
    "igreja",
    "comunidade",
    "congregação",
    "congregacao",
    "church",
    "assembly",
    "flock",
  ],
  cidade: [
    "cidade",
    "municipio",
    "localidade",
    "city",
    "town",
  ],
  endereco: [
    "endereco",
    "endereço",
    "rua",
    "logradouro",
    "address",
  ],
  celular: [
    "celular",
    "cel",
    "telefone",
    "tel",
    "phone",
    "contato",
    "fone",
    "telefone do participante",
    "celular do participante",
  ],
  whatsapp: [
    "whatsapp",
    "zap",
    "whats",
  ],
  email: [
    "e-mail",
    "email",
    "correo",
    "correio",
    "mail",
  ],
  responsavelNome: [
    "nome do responsável",
    "nome do responsavel",
    "responsavel",
    "responsável",
    "pai",
    "mae",
    "mãe",
    "father",
    "mother",
    "parent",
    "guardian",
    "responsavel 1",
    "responsável 1",
  ],
  responsavelTelefone: [
    "telefone",
    "telefone do responsavel",
    "telefone do responsável",
    "celular do responsavel",
    "celular do responsável",
    "contato do responsavel",
    "tel responsavel",
    "tel responsável",
  ],
  responsavelEmail: [
    "e-mail",
    "email do responsavel",
    "email do responsável",
    "e-mail do responsavel",
  ],
  responsavelParentesco: [
    "parentesco",
    "grau de parentesco",
    "relationship",
    "kinship",
  ],
  contatoEmergenciaNome: [
    "nome do contato de emergência",
    "nome do contato de emergencia",
    "contato de emergência",
    "contato de emergencia",
    "emergência nome",
    "emergencia nome",
  ],
  contatoEmergenciaParentesco: [
    "parentesco do contato de emergência",
    "parentesco do contato de emergencia",
    "parentesco emergência",
    "parentesco emergencia",
  ],
  contatoEmergenciaTelefone: [
    "telefone de contato de emergência",
    "telefone de contato de emergencia",
    "tel contato emergência",
    "tel contato emergencia",
    "telefone emergência",
    "telefone emergencia",
  ],
  condicaoSaude: [
    "o participante possui alguma doença, comorbidade ou condição médica?",
    "o participante possui alguma doenca, comorbidade ou condicao medica?",
    "doença",
    "doenca",
    "comorbidade",
    "condição médica",
    "condicao medica",
    "condicao",
    "doença comorbidade condição",
  ],
  condicaoEspecificacao: [
    "se respondeu sim, especifique",
    "especifique",
    "especificação da condição",
    "especificacao da condicao",
    "se sim, especifique",
  ],
  deficiencia: [
    "possui alguma deficiência ou necessidade específica?",
    "possui alguma deficiencia ou necessidade especifica?",
    "deficiência",
    "deficiencia",
    "necessidade específica",
    "necessidade especifica",
  ],
  deficienciaEspecificacao: [
    "caso sim, qual?",
    "caso sim qual",
    "qual deficiência",
    "qual deficiencia",
    "especificação deficiência",
    "especificacao deficiencia",
  ],
  possuiAlergias: [
    "possui alergias?",
    "possui alergias",
    "tem alergias",
  ],
  alergias: [
    "quais alergias possui?",
    "quais alergias",
    "alergias",
    "alergia",
    "allergies",
    "allergy",
  ],
  alergiaReacao: [
    "qual reação costuma apresentar?",
    "qual reação",
    "qual reacao costuma apresentar",
    "reação alérgica",
    "reacao alergica",
    "reação",
    "reacao",
  ],
  alergiaMedicacao: [
    "qual medicação utiliza em caso de reação?",
    "qual medicacao utiliza em caso de reacao",
    "medicação para reação",
    "medicacao para reacao",
    "remédio para alergia",
    "medicamento alergia",
  ],
  utilizaMedicamentosContinuos: [
    "utiliza medicamentos de uso contínuo?",
    "utiliza medicamentos de uso continuo?",
    "usa medicamentos",
    "medicamento de uso contínuo",
    "medicamento de uso continuo",
  ],
  medicamentos: [
    "caso utilize, informe os medicamentos (nome, dose, horário e motivo)",
    "caso utilize, informe os medicamentos (nome, dose, horario e motivo)",
    "medicamentos",
    "medicamento",
    "remedios",
    "remédio",
    "remedio",
    "medicines",
    "medication",
    "meds",
    "uso de medicamentos",
    "informe os medicamentos",
  ],
  possuiRestricoesAlimentares: [
    "possui restrições alimentares?",
    "possui restricoes alimentares?",
    "tem restrições alimentares",
    "tem restricoes alimentares",
  ],
  restricoesAlimentares: [
    "quais restrições alimentares?",
    "quais restricoes alimentares",
    "restricoes alimentares",
    "restrições alimentares",
    "restricao alimentar",
    "restrição alimentar",
    "dieta",
    "diet",
    "food restrictions",
  ],
  possuiRestricoesFisicas: [
    "possui restrições para atividades físicas?",
    "possui restricoes para atividades fisicas?",
    "restrição física",
    "restricao fisica",
  ],
  restricoesFisicas: [
    "quais restrições?",
    "quais restricoes",
    "quais restrições físicas",
    "quais restricoes fisicas",
    "restrições físicas",
    "restricoes fisicas",
  ],
  outraInfoSaude: [
    "existe alguma outra informação relevante sobre a saúde do participante?",
    "existe alguma outra informacao relevante sobre a saude do participante?",
    "outra informação saúde",
    "outra informacao saude",
    "informação adicional saúde",
    "info adicional",
  ],
  declaracao: [
    "declaro que as informações prestadas são verdadeiras",
    "declaro que as informacoes prestadas sao verdadeiras",
    "declaração",
    "declaracao",
    "aceite",
    "termo",
  ],
  observacoes: [
    "observacoes",
    "observações",
    "obs",
    "obs.",
    "notes",
    "observations",
    "anotacoes",
    "anotações",
    "observacoes gerais",
  ],
};

export const IDENTIFIER_FIELDS = ["nome", "cpf", "email", "celular", "dataNascimento"] as const;

export const RECORD_KEY_PREFIX = "salt:participant:";
export const IDS_LIST_KEY = "salt:participants:ids";
export const COUNTER_KEY = "salt:participants:counter";
export const SEARCH_INDEX_PREFIX = "salt:participants:idx:";
export const MAPPINGS_KEY = "salt:import:mappings";
export const BATCH_KEY_PREFIX = "salt:import:batch:";
export const BATCHES_LIST_KEY = "salt:import:batches";
export const AUTH_USER_PREFIX = "salt:auth:user:";
export const AUTH_USERS_KEY = "salt:auth:users";
export const AUTH_SESSION_PREFIX = "salt:auth:session:";
export const STATS_CACHE_KEY = "salt:stats:cache";

export const ROLE_LABELS: Record<string, string> = {
  admin: "Administrador",
  saude: "Equipe de Saúde",
  lider: "Líder",
  recepcao: "Recepção",
};

export const PERMISSIONS = {
  admin: [
    "view_participants",
    "edit_participants",
    "edit_health",
    "add_observations",
    "import_data",
    "delete_participants",
    "manage_users",
    "view_dashboard",
  ],
  saude: [
    "view_participants",
    "edit_participants",
    "edit_health",
    "add_observations",
    "view_dashboard",
  ],
  lider: [
    "view_participants",
    "add_observations",
    "view_dashboard",
  ],
  recepcao: [
    "view_participants",
    "view_dashboard",
  ],
} as const;

export type Role = keyof typeof PERMISSIONS;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS][number];
